version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: atom-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-atom_db}
      POSTGRES_USER: ${POSTGRES_USER:-atom_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-local_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-atom_user} -d ${POSTGRES_DB:-atom_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
