# fly.toml file generated for atomic-calendar on 2024-07-20T16:23:22.075792

app = "atomic-calendar"
primary_region = "iad"

[build]
  dockerfile_app = "frontend-nextjs/app_build_docker/Dockerfile.fly"
  dockerfile_functions = "frontend-nextjs/project/functions/Dockerfile.fly"
  dockerfile_optaplanner = "frontend-nextjs/optaplanner_build_docker/Dockerfile.fly"
  dockerfile_python_agent = "backend/python_agent_build_docker/Dockerfile.fly"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 8080
  processes = ["functions"]

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"



[[services]]
  internal_port = 8081
  processes = ["optaplanner"]

  [[services.ports]]
    handlers = ["http"]
    port = 8081
    force_https = true

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[services]]
  processes = ["python-agent"]

[processes]
  app = "sh -c 'cd frontend-nextjs/app_build_docker && exec node server.js'"
  functions = "sh -c 'cd frontend-nextjs/project/functions && exec /app/start.sh'"
  optaplanner = "sh -c 'cd frontend-nextjs/optaplanner_build_docker/kotlin-quarkus && exec /deployments/run-java.sh'"
  python-agent = "sh -c 'cd backend/python_agent_build_docker && exec tail -f /dev/null'"
