# This is the tenants configuration file
# Tenants are used for Kibana multi-tenancy

global_tenant:
  reserved: true
  description: "Global tenant"

private_tenant:
  reserved: true
  description: "Private tenant"
