table:
  name: tenant_configs
  schema: public
array_relationships:
  - name: tenant_thirdparty_providers
    using:
      manual_configuration:
        column_mapping:
          app_id: app_id
          connection_uri_domain: connection_uri_domain
          tenant_id: tenant_id
        insertion_order: null
        remote_table:
          name: tenant_thirdparty_providers
          schema: public
